from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961b326eb910'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PROCESSANDO', 'CONCLUIDO', 'ERRO', name='budgetstatus'), nullable=True),
    sa.Column('valor_total_orcamento', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('budget_id', sa.UUID(), nullable=False),
    sa.Column('descricao_original', sa.String(), nullable=False),
    sa.Column('categoria', sa.Enum('GPU', 'FONTE', 'GABINETE', 'FAN', 'PLACA_MAE', 'CPU', 'RAM', 'ARMAZENAMENTO', 'COOLER', 'OUTRO', name='itemcategoria'), nullable=True),
    sa.Column('preco_orcamento', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status_scraping', sa.Enum('PENDENTE', 'CONCLUIDO', 'ERRO', name='scrapingstatus'), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('loja', sa.String(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('url_produto', sa.String(), nullable=True),
    sa.Column('coletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_prices')
    op.drop_table('items')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
